# Introduction {#sec:introduction}

<!-- An example of how to include text based on the language. The two chunks below shows how switching the toggle in the YAML header for french allows inclusion/rejection of a paragraph. -->

The ocean and environmental sciences are becoming increasingly interdisciplinary and technology-driven, which requires researchers to develop new approaches to summarize, handle, and disseminate the vast amounts of information being collected (Baumann et al., 2016; Farley et al., 2018; Jasny et al., 2011; Sandve et al., 2013). Despite these recent technological advances, the pressure to publish has led to an entrenched individual-focused work culture and reduced collaboration (Obradović, 2019; Staples et al., 2019). This has resulted in a lack of time and incentives to create reproducible work, yet reproducibility is a key tenet of the scientific process (Heesen, 2018; Leek & Peng, 2015; Munafò et al., 2020). In particular, the digital transformation has drawn attention to the importance of computational reproducibility, or the ability to attain consistent results with a dataset using the same code and methods (Leek & Peng, 2015; Peng, 2011). This is critical for advancing scientific work by allowing researchers to more effectively build off existing knowledge while minimizing duplication of effort (Boland et al., 2017; McKiernan et al., 2016; Wolkovich et al., 2012). With mounting human pressures on the marine environment, scientists face a growing sense of urgency to quickly and accurately study these complex systems (Baumann et al., 2016; Lowndes et al., 2017).

The Science Branch within Fisheries and Oceans and Oceans Canada (DFO) spans a range of diverse research topics and operations, yet is overwhelmed by many of the same issues affecting science globally, related to transparent, transferable, and reproducible workflows. Developing reproducible tools, particularly those that focus on data discovery and reporting, were identified as a potential remedy to these siloed work environments (Edwards et al., 2018; Gomez et al., 2021). In response to these needs, different teams within DFO have developed open-source software tools to address these problems:
TURN THIS INTO A LIST!!!!!
The Pacific Region has created multiple R-based tools for reproducible reporting including ones to generate technical reports and Canadian Science Advisory Secretariat (CSAS) documents (i.e., the csasdown R package; Anderson et al., 2022; https://github.com/pbs-assess/csasdown). For example, csasdown was used to create an automated Research Document to model the populations of 113 groundfish species (Anderson et al., 2019; see links within https://github.com/pbs-assess).
The Newfoundland and Labrador Region has developed interactive dashboards in support of stock assessment processes (Regular et al., 2020; https://github.com/PaulRegular/interactive-stock-assessment).
The Maritimes Region developed a reproducible atlas technical report in 2012 to model the population status, important habitat, temperature and salinity preferences for 104 fish and invertebrate species (Ricard & Shackell, 2013). This atlas is currently being updated (Ricard & Gomez, 2021; https://github.com/dfo-gulf-science/Maritimes-SUMMER-Atlas) and a similar approach is currently underway in the Gulf Region. Further, a collaborative framework was developed to assess and monitor Marine Protected Areas, where all data assimilation and associated methods were encoded in R (Choi et al., 2018; https://github.com/jae0/).

Projects and decisions within DFO can be controversial, complex, and resource-intensive (Doubleday et al., 1997; DFO, 2018). Continued advancement of reproducible reporting tools allows for increased efficiency, quality, and transparency by making workflows both repeatable and publicly available (Lowndes et al., 2017; Munafò et al., 2017).

The Strategic Science Planning and Program Integrity division in DFO Maritimes supports various projects and presents many opportunities to modernize data management and reporting practices. In 2018, requests to the division to identify and summarize the available DFO and non-DFO datasets within the Maritimes region were becoming increasingly frequent. Born out of frustration and a need for swift and effective approaches, a team of self-proclaimed Strategic Reproducible Analytical Pipeline (RAP) Champions was formed to automate the creation of these reports. The primary objective of this initiative has been to develop a web-based tool to generate reproducible reports to identify and describe DFO and non-DFO datasets within a user-defined area. Specifically, we address internal requests that support processes that provide frequent and standardized advice, such as CSAS, Aquaculture Siting Responses, and Environmental Response, which typically focus on Species at Risk. We have encountered multiple challenges regarding data storage, access, and duplication of effort; therefore, a broad, secondary objective has been to spearhead discussions within DFO to advance reproducible workflows and improved data management practices, aligned with Open Government mandates to make information more accessible to everyone (DFO, 2020; Gomez et al. 2021; PCO, 2018; SCC, 2021). This technical report provides an overview of the work done so far to create this Spatial Reproducible Reporting Tool including a description of the workflow and code, lessons learned, and future directions. We present a snapshot of the progress made in the hopes that these efforts, while fulfilling a specific reporting need, will also facilitate increased collaboration and reproducibility in monitoring and research relevant to decision-making within DFO. 


