# REPORT USE: AUDIENCE OF THE SPATIAL REPRODUCIBLE REPORTING TOOL

## Planning for Integrated Environmental Response 
The Fisheries and Oceans Canada (DFO) Science Branch provides support to lead agencies during ship source marine oil spill incidents and exercises in a number of ways. In particular, this includes the provision of scientific and technical information on environmental sensitivities present in the incident area. During the initial emergency phase of an incident response, the (Planning for Integrated Environmental Response (PIER)) initiative works to develop a list of biological and ecological sensitivities in the spill area. This list of sensitivities is then incorporated into the initial departmental Resources at Risk list, used to assist in planning response strategies to mitigate environmental impact. The dynamic nature of oil spill response is such that information must flow quickly and efficiently to the appropriate responders, enabling an effective response in changing incident conditions. The Reproducible Reporting initiative has assisted the PIER team in incorporating science information from a variety of authoritative sources.

The different phases of environmental response require varying degrees of information; the initial emergency phase requires high-level information quickly, and once the response is underway information provided can become more in-depth. With this in mind, the PIER team may use all sections of the Reproducible Report throughout a response, and depending on trajectory modeling, will likely require a new Report to be generated. In the initial phase of the response, the Report is useful for synthesizing information on Species at Risk (or species under consideration for listing), Critical Habitats, Ecologically and Biologically Sensitive Areas (EBSAs) and Marine Protected Areas (MPAs). As the response evolves, additional focus can be placed on other species within the search area, while incorporating species group vulnerability to oil products, and considering the fate and behaviour of the spilled product in the marine environment.

Marine oil spill incidents come in many shapes and sizes, from minor to major geographic scales, and the Spatial Reproducible Reporting Tool provides the flexibility required to meet this challenge. Typically, PIER has used the tool at a relatively small scale (approximated 5 - 50 km^2^) in the near shore environment (e.g., vessel grounding), though Reports have also been requested for offshore areas (e.g., sunken vessel). 

The PIER team began using the Reports regularly in March 2021, and have relied on their information on at least ten occasions (two spill incidents, five spill exercises, and three planning processes) since then. With the development of the Spatial Reproducible Reporting Tool, PIER is able to combine the Report with other sources of information to provide more in-depth sensitivities lists within four to five hours of a pollution report. Improvements have been noted in not only speed but also in the depth and breadth of data available to synthesize. 

From an Environmental Response perspective, the Spatial Reproducible Reporting Tool could be improved to allow broader DFO individual user access and customizable Reports, as well as continued database inclusion. The inclusion of oil spill vulnerability scores in the Reports would be highly useful in environmental response, as would access to authoritative species fact sheets on species present within the search area. Overall, the continued evolution of the tool will improve the ability to meet PIER and DFO objectives related to Environmental Response.

## Aquaculture Siting

Fisheries and Oceans Canada (DFO) Maritimes Region participates in the review of applications for proposed new and amended marine finfish aquaculture sites. These applications are submitted by industry proponents to the provinces (Nova Scotia and New Brunswick) who then engage with other provincial and federal network agency partners for review and comment. As per the Canada-New Brunswick and Canada-Nova Scotia Memorandums of Understanding on Aquaculture Development, DFO reviews submitted applications and provides advice in relation to DFO’s legislative mandate.

DFO undertakes a multi-sectoral review process that especially focuses on potential impacts to fish and fish habitat. To help inform DFO’s review of each application, DFO Science advice is requested on the Predicted Exposure Zones (PEZs) associated with the range of aquaculture activities, and the predicted impacts on susceptible fish and fish habitat, including sensitive Species at Risk (SAR), susceptible fishery species, and the habitats that support them.
DFO receives baseline information in the application that is collected by the proponent as required by the Aquaculture Activities Regulations [@DFO2022_AAR]. This includes a current meter record of at least thirty days from within the proposed lease. DFO Science estimates PEZs using this proponent-collected current data. PEZs are precautionary overestimates used as a tool for identifying, albeit at a larger spatial scale, areas of potential overlap with species and habitats that are sensitive to exposures of organic loading, and any fish health treatment products, if used. 
The size of a PEZ is site-dependent, but has typically been on the order of hundreds of meters to kilometers away from the proposed site. While information from a fish and fish habitat survey is also submitted by the proponent as part of the baseline requirements, there are limitations to using this information as the requirements are focused on the immediate vicinity of the lease area at one point in time. 

Because of this, DFO Science’s participation in the review of aquaculture site applications was one of the earliest motivations behind development of the Spatial Reproducible Reporting Tool. The tool is used to search the PEZs for an efficient and consistent way of gaining an indication of species and habitats that have been observed within the PEZs, and therefore may be exposed to organic matter and/or fish health treatment products from the proposed site. To provide the advice requested of DFO Science, there is a focus on information related to SAR listed under Schedule 1 of the Species at Risk Act, fishery species, Ecologically Significant Species (ESS), and their associated habitats, as well as EBSAs. The records returned from the tool are then used to guide further consultation with species and subject matter experts about aspects such as spatial and temporal distribution in the area, uniqueness to the area, and whether or not they may be susceptible to exposures from the proposed aquaculture site.  

Review:

Line 515: In addition to mentioning PIER here you could give this groups new name and acronym (IMERP) I actually don't know what the entire name is right now though.
\pagebreak
