# My Discussion

In a direct response to repeat requests for data reports, we have developed a Spatial Reproducible Reporting Tool to display species data within a user-defined area of interest. By coding with R and R Markdown, in conjunction with Git and GitHub for version control, we have developed a tool to increase the efficiency and transparency for Science responses. This tool is developed for data-discovery, and currently summarizes over thirty sources, primarily focusing on Species at Risk, from DFO and non-DFO data. Reports can be rendered in under four minutes, resulting in a quantifiable reduction of time and resources spent acquiring and manipulating data into the required format. Ultimately, this aligns with the goals of reproducible data science globally, within the Canadian Government, and DFO.

Open data tools have underpinned the success of this work, and allowed us to drastically decrease the amount of time spent creating each Report. Specifically, R and R Markdown have been revolutionary by allowing us to move from archaic approaches of data collection, management, and visualization, to more modernized timesaving “digital” methods [@Lowndes2017]. Previously, data were stored in multiple locations, and we were often unaware of important datasets. Spending time compiling this data, and making this code available for repeat requests, helps mitigate against the continued challenges of shifting or evolving teams [@Wilson2014], and instead helps preserve institutional memory [@Wilson2017]. A supportive online community and other coders within DFO have greatly contributed to the advancement of this work, as we are made aware of new methods and approaches to improve our workflows. The adoption of Git and GitHub was also key to continue growing and expanding this work. Throughout the years, the Spatial Reproducible Reporting Tool has been through multiple adaptations, both large and small. Using a version control system allowed team members to code more collaboratively, make changes, test new algorithms, explore better visualization, and optimize data storage methods. Importantly, the version control system allows the team to revert to a previous version if necessary. This work can be slow and gradual, yet we consider it necessary to make our work reproducible and ultimately add to the cumulative knowledge in the scientific process [@Boland2017; @McKiernan2016; @Wolkovich2012].

Computing skills are increasingly important in science [@Baker2016; @Boettiger2015], yet many scientists are not formally trained in these practices [@Daniel2019; @Lowndes2017]. A lack of exposure and confidence in their abilities can often cause individuals to be resistant or hesitant to incorporate these tools into their work [@Lowndes2017]. This has several important consequences for DFO. In the workplace, scientists often do not have the time to learn in-depth computing skills, beyond focusing on immediate problems (Ram, 2013). DFO is increasingly offering more opportunities for professional development, and we see significant value in building a culture where these skills are valued, taught and practiced. For example, in 2022, the R Learning and Development Series organized lectures run by inSileco, to cover topics of open data science, which included smaller breakout groups for hands-on practice with these tools. Often, there are many tangible benefits of using a few simple commands for tasks such as transferring code, organizing versions of files, and collaborating in groups [@Blischak2016]. Introducing reproducible and open workflows will likely not yield immediate results or benefits [@Janssen2012], but instead is an incremental practice requiring patience, motivation, and sustained effort [@Peng2011; @Wilson2017].  

While the opportunities to champion reproducible workflows are endless, we remain cognizant of our limits, and often need to reign in our ambitions. Scope creep is routinely identified as one of the most common reasons for failure in software project management [@Bjarnason2012; @Komal2020; @Kumari2013], and our team confronts similar challenges on a consistent basis. We have been highly encouraged by the feedback and willingness to collaborate, yet each discussion brings new questions and ideas, and we are often pulled in multiple different directions to accommodate these requests. Our focus on co-creation remains key for prioritization and accountability, to ensure that our work is truly helpful to the DFO community. That said, we also value the continued advancement of new skills, intrinsic curiosity, and the pursuit of new opportunities, and this has been a major factor in our success in overcoming various frustrating obstacles. We acknowledge that there is no perfect balance for managing these competing and conflicting tasks and interests, but this can be at least partially remedied by continuous scope prioritization and close cooperation within our team [@Bjarnason2012]. We have weekly meetings, an active Teams chat, and an open and understanding culture within our group. Although we are highly ambitious, we consider it especially important to have reasonable expectations for ourselves and team members, given the backdrop of the COVID-19 pandemic, and other challenging personal and global events that can hinder workplace productivity and wellbeing [@Cleary2020; @Sigahi2021]. 

The data revolution is drastically transforming government [@Abiteboul2019; @SCC2021], yet data management often remains a hindrance to productive use [@Daniel2019; @Tenopir2011]. Gomez et al. [-@Gomez2021] noted there are many challenges within DFO for spatial data analysis such as no central repository for spatial data, a lack of infrastructure, and limited data documentation. This tool helps us achieve some of these objectives in support of data discovery, and align efforts for open data policies globally [@Culina2018; @Kitchin2014; @Murray-Rust2008], within the Canadian Government [@PCO2018; @SCC2021], and with DFO’s Data Strategy [@DFO2020Strategy]. However, despite the various political, economic, social, operational, and technical benefits to making data open and reproducible [@Janssen2012; @Murray-Rust2008], the barriers and challenges of this warrant further attention. For example, Janssen et al. [-@Janssen2012] reviewed the myths of open data and open government, and listed over fifty potential barriers to publicizing data including task complexity, institutional make-up, and technical challenges. While there are data managers and custodians to pursue much of this work, such as the Marine Spatial Planning program and the Enterprise Data Hub (EDH; built as part of the Target Architecture for Data and Application Platform, TADAP), as the scientists who use, manage, and collect these data, we realized it was increasingly important to take a proactive approach to reduce silos and increase communication between groups. We have attempted to lead discussions to make data sharing more interoperable, free and open, connect various groups, and avoid duplication of effort to address shared concerns. Ultimately, data management is a large task and requires participation at all levels to ensure we are making the best use of the available resources. 

DFO collects a wealth of data, yet in various instances, datasets not initially intended for spatial analysis contain useful information for our Report to strengthen decision-making. Our work focuses on automation, and these datasets require significant data wrangling to identify, extract, and integrate this information into a usable form [@Furche2016; @Kandel2011]. For example, funding agencies often focus on threats facing Species at Risk as part of their research priorities. There is great potential for this tool to identify and provide this threat information alongside the Species at Risk observed within a search area, and we have started this work within our Human Activities module. However, threats are mentioned in many of the documents mentioned in the SARA recovery planning process, and contain various levels of detail. Threat information can be mentioned in paragraphs, tables, sentences, or point form, and range from highly qualitative to quantitative, and these documents have gone through multiple generations of changes to further refine and define how to characterize threats [@DFO2007; @DFO2010; @DFO2014]. We are currently in discussion with our collaborators for ways to best summarize threat information so it is comprehensive, current, and accurate, to achieve these goals. We have also encountered additional challenges with non-standardized formats when undergoing an additional data mining and wrangling exercise to extract Species at Risk data from Section 73 permits which are used when a human activity affects listed wildlife species (e.g., developments, research purposes; SARA s.73, 2002). They often contain a mix of digital and hand-written documentation, have coordinate information in multiple formats, or in several instances, provide limited to no spatial context. Other sectors have recognized these challenges and are in discussion to standardize these approaches in future years. Advancements in big data and reproducible approaches cause excitement, yet there are stark warnings that irresponsible data wrangling within reproducible workflows can be misleading or draw incorrect conclusions [@Leek2015]. Aware of these challenges, we continue to be careful, measured, and consistently consult species experts to guide our work, and provide credible information without losing important context.

There are many potential future directions and opportunities within DFO to pursue this work  through the continued development of the Spatial Reproducible Reporting Tool, and its corresponding influence on data practices in the department. We have presented only a single application of the reproducible analytical pipelines developed in this work. The highly agile workflows created for data wrangling and processing could allow more complex issues to be addressed with reduced overhead, such as multi-species and multi-threat approaches, and more tailored aquaculture siting or environmental response reporting. We have other grand aspirations such as expanding this work into other regions in DFO, creating version(s) of the App that can be made available to the public, introducing these workflows to freshwater ecosystems, adding Aquatic Invasive Species data, and incorporating the widespread co-creation and code review of the Reproducible Reports. These endeavors become increasingly feasible as the data pipelines become more streamlined; however, this project is still heavily dependent on funding streams each year, which will influence our future directions. Beyond working within the confines of the existing workflows, their modularity allows individual components to be rapidly exported into other projects. Ongoing development of R packages to encompass widely applicable sections of this work can enhance the scope of pipelines across DFO and beyond. 
