# CONCLUSIONS

This technical report described a successful, innovative and cross-sectoral initiative for providing consistent and efficient DFO and non-DFO information relevant to decision-making. Our motivation is driven by tangible examples of peer-support, collaboration and workflow efficiency: reports assembled in the past using traditional approaches took weeks to be created, in comparison, this tool reduced the time to minutes, with a broader set of contextual information. This work has significantly increased reporting quality and efficiency for staff who generate/provide information, assemble reports with information from a variety of sources, and are accountable for providing information and advice in a timely fashion. In support of traceable, open science, and digital open government, this spatial tool includes a record of the underlying data analytics and provenance through curated version control (i.e., Git). The growing partnership of Strategic RAP Champions, collaborators, and advisors will continue to break silos and will expand as long as we can continue to foster growth, opportunities, peer-support, and training. We are committed to continue bringing partners together to support the strategic vision and priorities of DFO, aligned with individual research interests. 

\pagebreak