# ACKNOWLEDGMENTS

The Marine Spatial Planning (2019-2021), Nature Legacy (2020-2022), and SARA programs (2021-2022) have supported the Spatial Reproducible Reporting initiative in the Maritimes Region. This initiative would not have been possible without the inspiration, advice, and support from multiple colleagues that have contributed to different stages of this project, including  (listed in alphabetical order): Amanda Babin, Andrea Morden, Angelia Vanderlaan, Caroline Bakelaar, Brent Law, Brian Bower, Christine Stortini, Clark Richards, Colin O’Neil, David Fishman, Dan Ricard, Diane Amirault-Langalis, Emma Marotte, Gregory Puncher, Heath Stone, Heather Bowlby, Hilary Moors-Murphy, Javier Murillo, Koren Spence, Laura Feyrer, Mike McMahon, Nancy Shackell, Nick Jeffery, Pamela Emery, Paul Regular, Phil Greyson, Ryan Stanley, Sarah Tuziak, Shelley Lang, Susan Heaslip, and Tanya Pelrine. Great appreciation is addressed to (in alphabetical order) Biljana Narancic, Bruce Delo, Caroline Vanier, Claude Nozères, Jonathan Pye, and Virginie Roy for the helpful discussions and ideas generated during the various hackathon sessions. Additional thanks are addressed to reviewers Jake Coates and Mike McMahon for their time, edits, and suggestions to the text. We would also like to specifically thank Tana Worcester for her guidance, encouragement, and unending support throughout all stages of this initiative.
\pagebreak